# Generated by Django 4.2.2 on 2023-07-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('population', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('gdp', models.FloatField(default=0)),
                ('gdp_ppp', models.FloatField(default=0)),
                ('fertility_rate', models.FloatField(default=0)),
                ('median_age', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'countries',
                'ordering': ['name'],
            },
        ),
    ]
